services:
  frontend-blog:
    build:
      context: ./client
      dockerfile: Dockerfile
      tags:
        - "0.1.0"
    ports:
      - 3000:3000
    depends_on:
      user_service:
        condition: service_started
        restart: true
      post_service:
        condition: service_started
        restart: true
      comment_service:
        condition: service_started
        restart: true
    restart: on-failure
    volumes:
      - ./wid:/app/frontend

  # user_service:
  #   build:
  #     context: 
  #     dockerfile: 
  #   ports:
  #     - 8001:8001
  #   depends_on:
  #     - postgres-db

  # comment_service:
  # post_service: